//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Microsoft.IdentityModel.Analyzers {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Microsoft.IdentityModel.Analyzers.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type names should be all uppercase..
        /// </summary>
        internal static string AnalyzerDescription1 {
            get {
                return ResourceManager.GetString("AnalyzerDescription1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enclose statement with curly braces..
        /// </summary>
        internal static string AnalyzerDescription2 {
            get {
                return ResourceManager.GetString("AnalyzerDescription2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type shouldn&apos;t be used..
        /// </summary>
        internal static string AnalyzerDescription3 {
            get {
                return ResourceManager.GetString("AnalyzerDescription3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dependency found..
        /// </summary>
        internal static string AnalyzerDescription4 {
            get {
                return ResourceManager.GetString("AnalyzerDescription4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type name &apos;{0}&apos; contains lowercase letters.
        /// </summary>
        internal static string AnalyzerMessageFormat1 {
            get {
                return ResourceManager.GetString("AnalyzerMessageFormat1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to `{` brace expected..
        /// </summary>
        internal static string AnalyzerMessageFormat2 {
            get {
                return ResourceManager.GetString("AnalyzerMessageFormat2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type name &apos;{0}&apos; should not be used..
        /// </summary>
        internal static string AnalyzerMessageFormat3 {
            get {
                return ResourceManager.GetString("AnalyzerMessageFormat3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{0}&apos; version &apos;{1}&apos; dependency found..
        /// </summary>
        internal static string AnalyzerMessageFormat4 {
            get {
                return ResourceManager.GetString("AnalyzerMessageFormat4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type name contains lowercase letters.
        /// </summary>
        internal static string AnalyzerTitle1 {
            get {
                return ResourceManager.GetString("AnalyzerTitle1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enclose statement with curly braces.
        /// </summary>
        internal static string AnalyzerTitle2 {
            get {
                return ResourceManager.GetString("AnalyzerTitle2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type shouldn&apos;t be used..
        /// </summary>
        internal static string AnalyzerTitle3 {
            get {
                return ResourceManager.GetString("AnalyzerTitle3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dependency found..
        /// </summary>
        internal static string AnalyzerTitle4 {
            get {
                return ResourceManager.GetString("AnalyzerTitle4", resourceCulture);
            }
        }
    }
}
