name: "Run unit tests"

permissions:
  contents: read
  pull-requests: write

on:
  push:
    branches:
      - dev
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
      - ready_for_review
    branches:
      - dev

env:
  TargetNetNext: False

jobs:
  build:
    runs-on: windows-latest
    continue-on-error: false

    name: "Build and run unit tests"
    steps:
    - name: Set git core.longpaths flag
      run: |
          git config --system core.longpaths true

    - name: Checkout repository
      uses: actions/checkout@v5

    - name: Setup .NET 6.x
      uses: actions/setup-dotnet@v5
      with:
        dotnet-version: '6.x'

    - name: Setup .NET SDK from global.json
      uses: actions/setup-dotnet@v5
      with:
        global-json-file: ./global.json

    - name: Strong name bypass
      run: |
          regedit /s .\build\strongNameBypass.reg

    - name: Run the tests
      run: dotnet test Wilson.sln --settings:./build/CodeCoverage.runsettings

    # Run baseline package validation
    - name: Pack
      run: dotnet pack Product.proj --no-restore --no-build
